### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by stevenosloan** [comment]
Oh jeeze, I kinda forgot about this repo. Thanks

**Comment by lookfirst** [comment]
Lol... i know, such a silly pull request but github makes it so easy...

**Comment by stevenosloan** [comment]
hah, no I think it's great. I hate to be the guy with old crusty repos, but
removing them doesn't seem much better.

You actually using this or just happened across it?

On Tuesday, April 21, 2015, Jon Stevens notifications@github.com wrote:

> Lol... i know, such a silly pull request but github makes it so easy...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stevenosloan/heroku-buildpack-apache/pull/1#issuecomment-95011057
> .

## 

Steven Sloan  |  Designer & Developer

**Comment by lookfirst** [comment]
I'm looking for a buildpack for apache so that I can setup an apache/mod_webdav dyno that will be used as a test harness (via travis) for the [sardine project](https://github.com/lookfirst/sardine). Unfortunately, yours is not complete enough for me to just borrow and modify. I need one that compiles a recent version of apache. I will probably just modify another nginx one that I've been using which does compile it. Thanks though!

**Comment by stevenosloan** [comment]
ah cool, similar to when I modified this one almost 2 years ago -- just
enough to get a job done. Best of luck!

On Wednesday, April 22, 2015, Jon Stevens notifications@github.com wrote:

> I'm looking for a buildpack for apache so that I can setup an
> apache/mod_webdav dyno that will be used as a test harness (via travis) for
> the sardine project https://github.com/lookfirst/sardine.
> Unfortunately, yours is not complete enough for me to just borrow and
> modify. I need one that compiles a recent version of apache. I will
> probably just modify another nginx one that I've been using which does
> compile it. Thanks though!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stevenosloan/heroku-buildpack-apache/pull/1#issuecomment-95023579
> .

## 

Steven Sloan  |  Designer & Developer

**Comment by lookfirst** [comment]
Just fyi, I made one that is pretty simple and nice... https://github.com/lookfirst/heroku-buildpack-apache/

**Pull request merged**
